# config/database.yml

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: hello_world_app_development
  host: localhost
  username: hello_world_app
  password: <%= ENV['HELLO_WORLD_APP_DATABASE_PASSWORD'] %>

test:
  <<: *default
  database: hello_world_app_test
  host: localhost
  username: hello_world_app
  password: <%= ENV['HELLO_WORLD_APP_DATABASE_PASSWORD'] %>

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>